version: '3.8'

services:

  db:
    container_name: my_sql
    image: mysql
    restart: always
    ports:
      - 5436:5436
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}

  dbadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  app:
    container_name: app
    build: .
    command: bash -c "uvicorn src.study_load.app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
